puts "The Members of Sky High"
puts "--Faculty--"
puts "Principal Powers"
puts "Coach Boomer"
puts "Professor Medulla"
puts "All-American Boy"
puts "Ron Wilson, Bus Driver"
puts "Nurse Spex"
puts "--Students--"
puts "Will Stronghold"
puts "Layla Williams"
puts "Gwen Grayson"
puts "Warren Peace"
puts "Ethan Bank"
puts "Magenta Lewis"
puts "Zach Braun"
puts "Penny Lent"
puts "Lash"
puts "Speed"
print "Overall, we have "
print 10
puts " great students!"